name: Deploy to EC2
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync code to EC2
        run: |
          rsync -avz --delete \
            --exclude ".git*" --exclude "node_modules" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/geary-bot/

      - name: Install and restart
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<'EOF'
            set -e
            cd /opt/geary-bot
            npm ci --omit=dev            # reproducible install
            sudo systemctl restart geary-bot
          EOF
